/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as testTestImport } from './routes/(test)/_test'
import { Route as testExamplesImport } from './routes/(test)/_examples'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as testTestTestImport } from './routes/(test)/_test/test_'
import { Route as testTestTestAImport } from './routes/(test)/_test/test.a_'
import { Route as testTestTestASomethingImport } from './routes/(test)/_test/test.a.something'
import { Route as testTestTestABImport } from './routes/(test)/_test/test.a.b_'
import { Route as testTestTestABCImport } from './routes/(test)/_test/test.a.b.c'

// Create Virtual Routes

const testImport = createFileRoute('/(test)')()
const appUnauthorizedLazyImport = createFileRoute('/(app)/unauthorized')()
const appTermsLazyImport = createFileRoute('/(app)/terms')()
const appStatusLazyImport = createFileRoute('/(app)/status')()
const appPrivacyLazyImport = createFileRoute('/(app)/privacy')()
const testExamplesExamplesLazyImport = createFileRoute(
  '/(test)/_examples/examples_',
)()
const testExamplesExamplesTypographyLazyImport = createFileRoute(
  '/(test)/_examples/examples/typography',
)()
const testExamplesExamplesTablesLazyImport = createFileRoute(
  '/(test)/_examples/examples/tables',
)()
const testExamplesExamplesQueryLazyImport = createFileRoute(
  '/(test)/_examples/examples/query',
)()
const testExamplesExamplesNavigationLazyImport = createFileRoute(
  '/(test)/_examples/examples/navigation',
)()
const testExamplesExamplesLoadersLazyImport = createFileRoute(
  '/(test)/_examples/examples/loaders',
)()
const testExamplesExamplesFormsLazyImport = createFileRoute(
  '/(test)/_examples/examples/forms',
)()
const testExamplesExamplesDialogsLazyImport = createFileRoute(
  '/(test)/_examples/examples/dialogs',
)()
const testExamplesExamplesDatabaseLazyImport = createFileRoute(
  '/(test)/_examples/examples/database',
)()
const testExamplesExamplesContainersLazyImport = createFileRoute(
  '/(test)/_examples/examples/containers',
)()
const testExamplesExamplesColorsLazyImport = createFileRoute(
  '/(test)/_examples/examples/colors',
)()
const testExamplesExamplesBasicLazyImport = createFileRoute(
  '/(test)/_examples/examples/basic',
)()

// Create/Update Routes

const testRoute = testImport.update({
  id: '/(test)',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const appUnauthorizedLazyRoute = appUnauthorizedLazyImport
  .update({
    id: '/(app)/unauthorized',
    path: '/unauthorized',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(app)/unauthorized.lazy').then((d) => d.Route))

const appTermsLazyRoute = appTermsLazyImport
  .update({
    id: '/(app)/terms',
    path: '/terms',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(app)/terms.lazy').then((d) => d.Route))

const appStatusLazyRoute = appStatusLazyImport
  .update({
    id: '/(app)/status',
    path: '/status',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(app)/status.lazy').then((d) => d.Route))

const appPrivacyLazyRoute = appPrivacyLazyImport
  .update({
    id: '/(app)/privacy',
    path: '/privacy',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(app)/privacy.lazy').then((d) => d.Route))

const testTestRoute = testTestImport.update({
  id: '/_test',
  getParentRoute: () => testRoute,
} as any)

const testExamplesRoute = testExamplesImport.update({
  id: '/_examples',
  getParentRoute: () => testRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const testExamplesExamplesLazyRoute = testExamplesExamplesLazyImport
  .update({
    id: '/examples_',
    path: '/examples',
    getParentRoute: () => testExamplesRoute,
  } as any)
  .lazy(() =>
    import('./routes/(test)/_examples/examples_.lazy').then((d) => d.Route),
  )

const testTestTestRoute = testTestTestImport.update({
  id: '/test_',
  path: '/test',
  getParentRoute: () => testTestRoute,
} as any)

const testExamplesExamplesTypographyLazyRoute =
  testExamplesExamplesTypographyLazyImport
    .update({
      id: '/examples/typography',
      path: '/examples/typography',
      getParentRoute: () => testExamplesRoute,
    } as any)
    .lazy(() =>
      import('./routes/(test)/_examples/examples.typography.lazy').then(
        (d) => d.Route,
      ),
    )

const testExamplesExamplesTablesLazyRoute = testExamplesExamplesTablesLazyImport
  .update({
    id: '/examples/tables',
    path: '/examples/tables',
    getParentRoute: () => testExamplesRoute,
  } as any)
  .lazy(() =>
    import('./routes/(test)/_examples/examples.tables.lazy').then(
      (d) => d.Route,
    ),
  )

const testExamplesExamplesQueryLazyRoute = testExamplesExamplesQueryLazyImport
  .update({
    id: '/examples/query',
    path: '/examples/query',
    getParentRoute: () => testExamplesRoute,
  } as any)
  .lazy(() =>
    import('./routes/(test)/_examples/examples.query.lazy').then(
      (d) => d.Route,
    ),
  )

const testExamplesExamplesNavigationLazyRoute =
  testExamplesExamplesNavigationLazyImport
    .update({
      id: '/examples/navigation',
      path: '/examples/navigation',
      getParentRoute: () => testExamplesRoute,
    } as any)
    .lazy(() =>
      import('./routes/(test)/_examples/examples.navigation.lazy').then(
        (d) => d.Route,
      ),
    )

const testExamplesExamplesLoadersLazyRoute =
  testExamplesExamplesLoadersLazyImport
    .update({
      id: '/examples/loaders',
      path: '/examples/loaders',
      getParentRoute: () => testExamplesRoute,
    } as any)
    .lazy(() =>
      import('./routes/(test)/_examples/examples.loaders.lazy').then(
        (d) => d.Route,
      ),
    )

const testExamplesExamplesFormsLazyRoute = testExamplesExamplesFormsLazyImport
  .update({
    id: '/examples/forms',
    path: '/examples/forms',
    getParentRoute: () => testExamplesRoute,
  } as any)
  .lazy(() =>
    import('./routes/(test)/_examples/examples.forms.lazy').then(
      (d) => d.Route,
    ),
  )

const testExamplesExamplesDialogsLazyRoute =
  testExamplesExamplesDialogsLazyImport
    .update({
      id: '/examples/dialogs',
      path: '/examples/dialogs',
      getParentRoute: () => testExamplesRoute,
    } as any)
    .lazy(() =>
      import('./routes/(test)/_examples/examples.dialogs.lazy').then(
        (d) => d.Route,
      ),
    )

const testExamplesExamplesDatabaseLazyRoute =
  testExamplesExamplesDatabaseLazyImport
    .update({
      id: '/examples/database',
      path: '/examples/database',
      getParentRoute: () => testExamplesRoute,
    } as any)
    .lazy(() =>
      import('./routes/(test)/_examples/examples.database.lazy').then(
        (d) => d.Route,
      ),
    )

const testExamplesExamplesContainersLazyRoute =
  testExamplesExamplesContainersLazyImport
    .update({
      id: '/examples/containers',
      path: '/examples/containers',
      getParentRoute: () => testExamplesRoute,
    } as any)
    .lazy(() =>
      import('./routes/(test)/_examples/examples.containers.lazy').then(
        (d) => d.Route,
      ),
    )

const testExamplesExamplesColorsLazyRoute = testExamplesExamplesColorsLazyImport
  .update({
    id: '/examples/colors',
    path: '/examples/colors',
    getParentRoute: () => testExamplesRoute,
  } as any)
  .lazy(() =>
    import('./routes/(test)/_examples/examples.colors.lazy').then(
      (d) => d.Route,
    ),
  )

const testExamplesExamplesBasicLazyRoute = testExamplesExamplesBasicLazyImport
  .update({
    id: '/examples/basic',
    path: '/examples/basic',
    getParentRoute: () => testExamplesRoute,
  } as any)
  .lazy(() =>
    import('./routes/(test)/_examples/examples.basic.lazy').then(
      (d) => d.Route,
    ),
  )

const testTestTestARoute = testTestTestAImport.update({
  id: '/test/a_',
  path: '/test/a',
  getParentRoute: () => testTestRoute,
} as any)

const testTestTestASomethingRoute = testTestTestASomethingImport.update({
  id: '/test/a/something',
  path: '/test/a/something',
  getParentRoute: () => testTestRoute,
} as any)

const testTestTestABRoute = testTestTestABImport.update({
  id: '/test/a/b_',
  path: '/test/a/b',
  getParentRoute: () => testTestRoute,
} as any)

const testTestTestABCRoute = testTestTestABCImport.update({
  id: '/test/a/b/c',
  path: '/test/a/b/c',
  getParentRoute: () => testTestRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof rootRoute
    }
    '/(test)': {
      id: '/(test)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof testImport
      parentRoute: typeof rootRoute
    }
    '/(test)/_examples': {
      id: '/(test)/_examples'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof testExamplesImport
      parentRoute: typeof testRoute
    }
    '/(test)/_test': {
      id: '/(test)/_test'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof testTestImport
      parentRoute: typeof testImport
    }
    '/(app)/privacy': {
      id: '/(app)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof appPrivacyLazyImport
      parentRoute: typeof rootRoute
    }
    '/(app)/status': {
      id: '/(app)/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof appStatusLazyImport
      parentRoute: typeof rootRoute
    }
    '/(app)/terms': {
      id: '/(app)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof appTermsLazyImport
      parentRoute: typeof rootRoute
    }
    '/(app)/unauthorized': {
      id: '/(app)/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof appUnauthorizedLazyImport
      parentRoute: typeof rootRoute
    }
    '/(test)/_test/test_': {
      id: '/(test)/_test/test_'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof testTestTestImport
      parentRoute: typeof testTestImport
    }
    '/(test)/_examples/examples_': {
      id: '/(test)/_examples/examples_'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof testExamplesExamplesLazyImport
      parentRoute: typeof testExamplesImport
    }
    '/(test)/_test/test/a_': {
      id: '/(test)/_test/test/a_'
      path: '/test/a'
      fullPath: '/test/a'
      preLoaderRoute: typeof testTestTestAImport
      parentRoute: typeof testTestImport
    }
    '/(test)/_examples/examples/basic': {
      id: '/(test)/_examples/examples/basic'
      path: '/examples/basic'
      fullPath: '/examples/basic'
      preLoaderRoute: typeof testExamplesExamplesBasicLazyImport
      parentRoute: typeof testExamplesImport
    }
    '/(test)/_examples/examples/colors': {
      id: '/(test)/_examples/examples/colors'
      path: '/examples/colors'
      fullPath: '/examples/colors'
      preLoaderRoute: typeof testExamplesExamplesColorsLazyImport
      parentRoute: typeof testExamplesImport
    }
    '/(test)/_examples/examples/containers': {
      id: '/(test)/_examples/examples/containers'
      path: '/examples/containers'
      fullPath: '/examples/containers'
      preLoaderRoute: typeof testExamplesExamplesContainersLazyImport
      parentRoute: typeof testExamplesImport
    }
    '/(test)/_examples/examples/database': {
      id: '/(test)/_examples/examples/database'
      path: '/examples/database'
      fullPath: '/examples/database'
      preLoaderRoute: typeof testExamplesExamplesDatabaseLazyImport
      parentRoute: typeof testExamplesImport
    }
    '/(test)/_examples/examples/dialogs': {
      id: '/(test)/_examples/examples/dialogs'
      path: '/examples/dialogs'
      fullPath: '/examples/dialogs'
      preLoaderRoute: typeof testExamplesExamplesDialogsLazyImport
      parentRoute: typeof testExamplesImport
    }
    '/(test)/_examples/examples/forms': {
      id: '/(test)/_examples/examples/forms'
      path: '/examples/forms'
      fullPath: '/examples/forms'
      preLoaderRoute: typeof testExamplesExamplesFormsLazyImport
      parentRoute: typeof testExamplesImport
    }
    '/(test)/_examples/examples/loaders': {
      id: '/(test)/_examples/examples/loaders'
      path: '/examples/loaders'
      fullPath: '/examples/loaders'
      preLoaderRoute: typeof testExamplesExamplesLoadersLazyImport
      parentRoute: typeof testExamplesImport
    }
    '/(test)/_examples/examples/navigation': {
      id: '/(test)/_examples/examples/navigation'
      path: '/examples/navigation'
      fullPath: '/examples/navigation'
      preLoaderRoute: typeof testExamplesExamplesNavigationLazyImport
      parentRoute: typeof testExamplesImport
    }
    '/(test)/_examples/examples/query': {
      id: '/(test)/_examples/examples/query'
      path: '/examples/query'
      fullPath: '/examples/query'
      preLoaderRoute: typeof testExamplesExamplesQueryLazyImport
      parentRoute: typeof testExamplesImport
    }
    '/(test)/_examples/examples/tables': {
      id: '/(test)/_examples/examples/tables'
      path: '/examples/tables'
      fullPath: '/examples/tables'
      preLoaderRoute: typeof testExamplesExamplesTablesLazyImport
      parentRoute: typeof testExamplesImport
    }
    '/(test)/_examples/examples/typography': {
      id: '/(test)/_examples/examples/typography'
      path: '/examples/typography'
      fullPath: '/examples/typography'
      preLoaderRoute: typeof testExamplesExamplesTypographyLazyImport
      parentRoute: typeof testExamplesImport
    }
    '/(test)/_test/test/a/b_': {
      id: '/(test)/_test/test/a/b_'
      path: '/test/a/b'
      fullPath: '/test/a/b'
      preLoaderRoute: typeof testTestTestABImport
      parentRoute: typeof testTestImport
    }
    '/(test)/_test/test/a/something': {
      id: '/(test)/_test/test/a/something'
      path: '/test/a/something'
      fullPath: '/test/a/something'
      preLoaderRoute: typeof testTestTestASomethingImport
      parentRoute: typeof testTestImport
    }
    '/(test)/_test/test/a/b/c': {
      id: '/(test)/_test/test/a/b/c'
      path: '/test/a/b/c'
      fullPath: '/test/a/b/c'
      preLoaderRoute: typeof testTestTestABCImport
      parentRoute: typeof testTestImport
    }
  }
}

// Create and export the route tree

interface testExamplesRouteChildren {
  testExamplesExamplesLazyRoute: typeof testExamplesExamplesLazyRoute
  testExamplesExamplesBasicLazyRoute: typeof testExamplesExamplesBasicLazyRoute
  testExamplesExamplesColorsLazyRoute: typeof testExamplesExamplesColorsLazyRoute
  testExamplesExamplesContainersLazyRoute: typeof testExamplesExamplesContainersLazyRoute
  testExamplesExamplesDatabaseLazyRoute: typeof testExamplesExamplesDatabaseLazyRoute
  testExamplesExamplesDialogsLazyRoute: typeof testExamplesExamplesDialogsLazyRoute
  testExamplesExamplesFormsLazyRoute: typeof testExamplesExamplesFormsLazyRoute
  testExamplesExamplesLoadersLazyRoute: typeof testExamplesExamplesLoadersLazyRoute
  testExamplesExamplesNavigationLazyRoute: typeof testExamplesExamplesNavigationLazyRoute
  testExamplesExamplesQueryLazyRoute: typeof testExamplesExamplesQueryLazyRoute
  testExamplesExamplesTablesLazyRoute: typeof testExamplesExamplesTablesLazyRoute
  testExamplesExamplesTypographyLazyRoute: typeof testExamplesExamplesTypographyLazyRoute
}

const testExamplesRouteChildren: testExamplesRouteChildren = {
  testExamplesExamplesLazyRoute: testExamplesExamplesLazyRoute,
  testExamplesExamplesBasicLazyRoute: testExamplesExamplesBasicLazyRoute,
  testExamplesExamplesColorsLazyRoute: testExamplesExamplesColorsLazyRoute,
  testExamplesExamplesContainersLazyRoute:
    testExamplesExamplesContainersLazyRoute,
  testExamplesExamplesDatabaseLazyRoute: testExamplesExamplesDatabaseLazyRoute,
  testExamplesExamplesDialogsLazyRoute: testExamplesExamplesDialogsLazyRoute,
  testExamplesExamplesFormsLazyRoute: testExamplesExamplesFormsLazyRoute,
  testExamplesExamplesLoadersLazyRoute: testExamplesExamplesLoadersLazyRoute,
  testExamplesExamplesNavigationLazyRoute:
    testExamplesExamplesNavigationLazyRoute,
  testExamplesExamplesQueryLazyRoute: testExamplesExamplesQueryLazyRoute,
  testExamplesExamplesTablesLazyRoute: testExamplesExamplesTablesLazyRoute,
  testExamplesExamplesTypographyLazyRoute:
    testExamplesExamplesTypographyLazyRoute,
}

const testExamplesRouteWithChildren = testExamplesRoute._addFileChildren(
  testExamplesRouteChildren,
)

interface testTestRouteChildren {
  testTestTestRoute: typeof testTestTestRoute
  testTestTestARoute: typeof testTestTestARoute
  testTestTestABRoute: typeof testTestTestABRoute
  testTestTestASomethingRoute: typeof testTestTestASomethingRoute
  testTestTestABCRoute: typeof testTestTestABCRoute
}

const testTestRouteChildren: testTestRouteChildren = {
  testTestTestRoute: testTestTestRoute,
  testTestTestARoute: testTestTestARoute,
  testTestTestABRoute: testTestTestABRoute,
  testTestTestASomethingRoute: testTestTestASomethingRoute,
  testTestTestABCRoute: testTestTestABCRoute,
}

const testTestRouteWithChildren = testTestRoute._addFileChildren(
  testTestRouteChildren,
)

interface testRouteChildren {
  testExamplesRoute: typeof testExamplesRouteWithChildren
  testTestRoute: typeof testTestRouteWithChildren
}

const testRouteChildren: testRouteChildren = {
  testExamplesRoute: testExamplesRouteWithChildren,
  testTestRoute: testTestRouteWithChildren,
}

const testRouteWithChildren = testRoute._addFileChildren(testRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof testExamplesRouteWithChildren
  '/login': typeof authLoginRoute
  '': typeof testTestRouteWithChildren
  '/privacy': typeof appPrivacyLazyRoute
  '/status': typeof appStatusLazyRoute
  '/terms': typeof appTermsLazyRoute
  '/unauthorized': typeof appUnauthorizedLazyRoute
  '/test': typeof testTestTestRoute
  '/examples': typeof testExamplesExamplesLazyRoute
  '/test/a': typeof testTestTestARoute
  '/examples/basic': typeof testExamplesExamplesBasicLazyRoute
  '/examples/colors': typeof testExamplesExamplesColorsLazyRoute
  '/examples/containers': typeof testExamplesExamplesContainersLazyRoute
  '/examples/database': typeof testExamplesExamplesDatabaseLazyRoute
  '/examples/dialogs': typeof testExamplesExamplesDialogsLazyRoute
  '/examples/forms': typeof testExamplesExamplesFormsLazyRoute
  '/examples/loaders': typeof testExamplesExamplesLoadersLazyRoute
  '/examples/navigation': typeof testExamplesExamplesNavigationLazyRoute
  '/examples/query': typeof testExamplesExamplesQueryLazyRoute
  '/examples/tables': typeof testExamplesExamplesTablesLazyRoute
  '/examples/typography': typeof testExamplesExamplesTypographyLazyRoute
  '/test/a/b': typeof testTestTestABRoute
  '/test/a/something': typeof testTestTestASomethingRoute
  '/test/a/b/c': typeof testTestTestABCRoute
}

export interface FileRoutesByTo {
  '/': typeof testExamplesRouteWithChildren
  '/login': typeof authLoginRoute
  '': typeof testTestRouteWithChildren
  '/privacy': typeof appPrivacyLazyRoute
  '/status': typeof appStatusLazyRoute
  '/terms': typeof appTermsLazyRoute
  '/unauthorized': typeof appUnauthorizedLazyRoute
  '/test': typeof testTestTestRoute
  '/examples': typeof testExamplesExamplesLazyRoute
  '/test/a': typeof testTestTestARoute
  '/examples/basic': typeof testExamplesExamplesBasicLazyRoute
  '/examples/colors': typeof testExamplesExamplesColorsLazyRoute
  '/examples/containers': typeof testExamplesExamplesContainersLazyRoute
  '/examples/database': typeof testExamplesExamplesDatabaseLazyRoute
  '/examples/dialogs': typeof testExamplesExamplesDialogsLazyRoute
  '/examples/forms': typeof testExamplesExamplesFormsLazyRoute
  '/examples/loaders': typeof testExamplesExamplesLoadersLazyRoute
  '/examples/navigation': typeof testExamplesExamplesNavigationLazyRoute
  '/examples/query': typeof testExamplesExamplesQueryLazyRoute
  '/examples/tables': typeof testExamplesExamplesTablesLazyRoute
  '/examples/typography': typeof testExamplesExamplesTypographyLazyRoute
  '/test/a/b': typeof testTestTestABRoute
  '/test/a/something': typeof testTestTestASomethingRoute
  '/test/a/b/c': typeof testTestTestABCRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(auth)/login': typeof authLoginRoute
  '/(test)': typeof testRouteWithChildren
  '/(test)/_examples': typeof testExamplesRouteWithChildren
  '/(test)/_test': typeof testTestRouteWithChildren
  '/(app)/privacy': typeof appPrivacyLazyRoute
  '/(app)/status': typeof appStatusLazyRoute
  '/(app)/terms': typeof appTermsLazyRoute
  '/(app)/unauthorized': typeof appUnauthorizedLazyRoute
  '/(test)/_test/test_': typeof testTestTestRoute
  '/(test)/_examples/examples_': typeof testExamplesExamplesLazyRoute
  '/(test)/_test/test/a_': typeof testTestTestARoute
  '/(test)/_examples/examples/basic': typeof testExamplesExamplesBasicLazyRoute
  '/(test)/_examples/examples/colors': typeof testExamplesExamplesColorsLazyRoute
  '/(test)/_examples/examples/containers': typeof testExamplesExamplesContainersLazyRoute
  '/(test)/_examples/examples/database': typeof testExamplesExamplesDatabaseLazyRoute
  '/(test)/_examples/examples/dialogs': typeof testExamplesExamplesDialogsLazyRoute
  '/(test)/_examples/examples/forms': typeof testExamplesExamplesFormsLazyRoute
  '/(test)/_examples/examples/loaders': typeof testExamplesExamplesLoadersLazyRoute
  '/(test)/_examples/examples/navigation': typeof testExamplesExamplesNavigationLazyRoute
  '/(test)/_examples/examples/query': typeof testExamplesExamplesQueryLazyRoute
  '/(test)/_examples/examples/tables': typeof testExamplesExamplesTablesLazyRoute
  '/(test)/_examples/examples/typography': typeof testExamplesExamplesTypographyLazyRoute
  '/(test)/_test/test/a/b_': typeof testTestTestABRoute
  '/(test)/_test/test/a/something': typeof testTestTestASomethingRoute
  '/(test)/_test/test/a/b/c': typeof testTestTestABCRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | ''
    | '/privacy'
    | '/status'
    | '/terms'
    | '/unauthorized'
    | '/test'
    | '/examples'
    | '/test/a'
    | '/examples/basic'
    | '/examples/colors'
    | '/examples/containers'
    | '/examples/database'
    | '/examples/dialogs'
    | '/examples/forms'
    | '/examples/loaders'
    | '/examples/navigation'
    | '/examples/query'
    | '/examples/tables'
    | '/examples/typography'
    | '/test/a/b'
    | '/test/a/something'
    | '/test/a/b/c'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | ''
    | '/privacy'
    | '/status'
    | '/terms'
    | '/unauthorized'
    | '/test'
    | '/examples'
    | '/test/a'
    | '/examples/basic'
    | '/examples/colors'
    | '/examples/containers'
    | '/examples/database'
    | '/examples/dialogs'
    | '/examples/forms'
    | '/examples/loaders'
    | '/examples/navigation'
    | '/examples/query'
    | '/examples/tables'
    | '/examples/typography'
    | '/test/a/b'
    | '/test/a/something'
    | '/test/a/b/c'
  id:
    | '__root__'
    | '/'
    | '/(auth)/login'
    | '/(test)'
    | '/(test)/_examples'
    | '/(test)/_test'
    | '/(app)/privacy'
    | '/(app)/status'
    | '/(app)/terms'
    | '/(app)/unauthorized'
    | '/(test)/_test/test_'
    | '/(test)/_examples/examples_'
    | '/(test)/_test/test/a_'
    | '/(test)/_examples/examples/basic'
    | '/(test)/_examples/examples/colors'
    | '/(test)/_examples/examples/containers'
    | '/(test)/_examples/examples/database'
    | '/(test)/_examples/examples/dialogs'
    | '/(test)/_examples/examples/forms'
    | '/(test)/_examples/examples/loaders'
    | '/(test)/_examples/examples/navigation'
    | '/(test)/_examples/examples/query'
    | '/(test)/_examples/examples/tables'
    | '/(test)/_examples/examples/typography'
    | '/(test)/_test/test/a/b_'
    | '/(test)/_test/test/a/something'
    | '/(test)/_test/test/a/b/c'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLoginRoute: typeof authLoginRoute
  testRoute: typeof testRouteWithChildren
  appPrivacyLazyRoute: typeof appPrivacyLazyRoute
  appStatusLazyRoute: typeof appStatusLazyRoute
  appTermsLazyRoute: typeof appTermsLazyRoute
  appUnauthorizedLazyRoute: typeof appUnauthorizedLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLoginRoute: authLoginRoute,
  testRoute: testRouteWithChildren,
  appPrivacyLazyRoute: appPrivacyLazyRoute,
  appStatusLazyRoute: appStatusLazyRoute,
  appTermsLazyRoute: appTermsLazyRoute,
  appUnauthorizedLazyRoute: appUnauthorizedLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(auth)/login",
        "/(test)",
        "/(app)/privacy",
        "/(app)/status",
        "/(app)/terms",
        "/(app)/unauthorized"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx"
    },
    "/(test)": {
      "filePath": "(test)",
      "children": [
        "/(test)/_examples",
        "/(test)/_test"
      ]
    },
    "/(test)/_examples": {
      "filePath": "(test)/_examples.tsx",
      "parent": "/(test)",
      "children": [
        "/(test)/_examples/examples_",
        "/(test)/_examples/examples/basic",
        "/(test)/_examples/examples/colors",
        "/(test)/_examples/examples/containers",
        "/(test)/_examples/examples/database",
        "/(test)/_examples/examples/dialogs",
        "/(test)/_examples/examples/forms",
        "/(test)/_examples/examples/loaders",
        "/(test)/_examples/examples/navigation",
        "/(test)/_examples/examples/query",
        "/(test)/_examples/examples/tables",
        "/(test)/_examples/examples/typography"
      ]
    },
    "/(test)/_test": {
      "filePath": "(test)/_test.tsx",
      "parent": "/(test)",
      "children": [
        "/(test)/_test/test_",
        "/(test)/_test/test/a_",
        "/(test)/_test/test/a/b_",
        "/(test)/_test/test/a/something",
        "/(test)/_test/test/a/b/c"
      ]
    },
    "/(app)/privacy": {
      "filePath": "(app)/privacy.lazy.tsx"
    },
    "/(app)/status": {
      "filePath": "(app)/status.lazy.tsx"
    },
    "/(app)/terms": {
      "filePath": "(app)/terms.lazy.tsx"
    },
    "/(app)/unauthorized": {
      "filePath": "(app)/unauthorized.lazy.tsx"
    },
    "/(test)/_test/test_": {
      "filePath": "(test)/_test/test_.tsx",
      "parent": "/(test)/_test"
    },
    "/(test)/_examples/examples_": {
      "filePath": "(test)/_examples/examples_.lazy.tsx",
      "parent": "/(test)/_examples"
    },
    "/(test)/_test/test/a_": {
      "filePath": "(test)/_test/test.a_.tsx",
      "parent": "/(test)/_test"
    },
    "/(test)/_examples/examples/basic": {
      "filePath": "(test)/_examples/examples.basic.lazy.tsx",
      "parent": "/(test)/_examples"
    },
    "/(test)/_examples/examples/colors": {
      "filePath": "(test)/_examples/examples.colors.lazy.tsx",
      "parent": "/(test)/_examples"
    },
    "/(test)/_examples/examples/containers": {
      "filePath": "(test)/_examples/examples.containers.lazy.tsx",
      "parent": "/(test)/_examples"
    },
    "/(test)/_examples/examples/database": {
      "filePath": "(test)/_examples/examples.database.lazy.tsx",
      "parent": "/(test)/_examples"
    },
    "/(test)/_examples/examples/dialogs": {
      "filePath": "(test)/_examples/examples.dialogs.lazy.tsx",
      "parent": "/(test)/_examples"
    },
    "/(test)/_examples/examples/forms": {
      "filePath": "(test)/_examples/examples.forms.lazy.tsx",
      "parent": "/(test)/_examples"
    },
    "/(test)/_examples/examples/loaders": {
      "filePath": "(test)/_examples/examples.loaders.lazy.tsx",
      "parent": "/(test)/_examples"
    },
    "/(test)/_examples/examples/navigation": {
      "filePath": "(test)/_examples/examples.navigation.lazy.tsx",
      "parent": "/(test)/_examples"
    },
    "/(test)/_examples/examples/query": {
      "filePath": "(test)/_examples/examples.query.lazy.tsx",
      "parent": "/(test)/_examples"
    },
    "/(test)/_examples/examples/tables": {
      "filePath": "(test)/_examples/examples.tables.lazy.tsx",
      "parent": "/(test)/_examples"
    },
    "/(test)/_examples/examples/typography": {
      "filePath": "(test)/_examples/examples.typography.lazy.tsx",
      "parent": "/(test)/_examples"
    },
    "/(test)/_test/test/a/b_": {
      "filePath": "(test)/_test/test.a.b_.tsx",
      "parent": "/(test)/_test"
    },
    "/(test)/_test/test/a/something": {
      "filePath": "(test)/_test/test.a.something.tsx",
      "parent": "/(test)/_test"
    },
    "/(test)/_test/test/a/b/c": {
      "filePath": "(test)/_test/test.a.b.c.tsx",
      "parent": "/(test)/_test"
    }
  }
}
ROUTE_MANIFEST_END */
